rus:
  - Ru_index: ru_0
    bwps:
      - id: bwp_0
        num_prb: 30
        bandindex: 0  # numerology 0
        p_each_PRB: 5 # mW
  - Ru_index: ru_1
    bwps:
      - id: bwp_0
        num_prb: 30
        bandindex: 0  # numerology 0
        p_each_PRB: 5 # mW

