ues:
  # Các UE thuộc slice_urllc_0
  - id: ue_0
    slice_id: slice_urllc_0
    lat: 1.0 # ms
    pac: 256 # byte
    
  - id: ue_1
    slice_id: slice_urllc_0
    lat: 1.0 # ms
    pac: 256 # byte

  # Các UE thuộc slice_urllc_1
  - id: ue_0
    slice_id: slice_urllc_1
    lat: 1.0 # ms
    pac: 256 # byte
