mobility:
  high:
    r_max: 1000
    r_min: 500
    speed_max: 60
    speed_min: 30
  low:
    r_max: 1000
    r_min: 500
    speed_max: 5
    speed_min: 1
  stable:
    r_max: 1000
    r_min: 500
    speed_max: 0
    speed_min: 0
network:
  num_rus: 6
  ues_per_ru: 16
